# Ref: https://blog.finxter.com/how-to-run-tests-efficiently-in-pytest

[pytest]
addopts = -s -rA --tb=short --cov=src --cov-report=term-missing --cov-fail-under=80 --log-cli-level=WARNING
testpaths = tests/
