from typing import List, Optional, Protocol

from src.domain.category import Category


class CategoryRepository(Protocol):
    def get_by_id(self, category_id: int) -> Optional[Category]:
        """Busca una categoría por su ID."""
        ...

    def get_by_name(self, name: str) -> Optional[Category]: ...

    def create(self, category: Category) -> Category: ...

    def get_all(self) -> List[Category]: ...

    def update(self, category_id: int, category_data: dict) -> Category: ...

    def delete(self, category_id: int) -> None: ...
