from typing import List, Optional, Protocol, Mapping, Any

from src.domain.product import Product


class ProductRepository(Protocol):
    def create(self, product: Product) -> Product: ...

    def get_by_sku(self, sku: str) -> Optional[Product]: ...

    def get_all(self, skip: int = 0, limit: int = 100) -> List[Product]: ...

    def get_by_id(self, product_id: int) -> Optional[Product]: ...

    def update(self, product_id: int, product_data: Mapping[str, Any]) -> Product: ...

    def delete(self, product_id: int) -> None: ...

    def get_low_stock(self) -> List[Product]: ...
